### PR TITLE
Cdn

### PR DESCRIPTION
**Pull request by PeterDaveHello**
To speed up and make the repo thinner, easier to manage.

### CODE REVIEW

**Comment by jackycute** [comment]
Hello, very good to see you done this. I agreed with your point.
But if someone want to use this locally then will be a problem using cdn.
Is there any other choice can make?

**Comment by PeterDaveHello** [comment]
But you are already using cdn, e.g. 
https://github.com/jackycute/HackMD/blob/master/public/index.html#L18

So I don't think this is a new issue.

Produce a local version may be a possible solution.

**Comment by jackycute** [comment]
Oh my, your totally right, I missed that...
OK, I will merge your PR, thank you very much.

I'm consider using requireJS to do cdn fallback now.

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by jackycute** [comment]
Hello, I might fallback and not using cdn.
Because I found many people like to use this offline and internally, so it's better not use cdn.
Thank you anyway, andwe might have a plan to make a standalone app in the future.

**Comment by PeterDaveHello** [comment]
Maybe we can use a config to decide use it or use local files?

**Comment by jackycute** [comment]
That's a good idea, I will try it.

**Comment by PeterDaveHello** [comment]
I think config is good enough :smile:

**Comment by jackycute** [comment]
Hey, I've add useCDN option, take a look!

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
